spring.application.name=SB-Mail_Send


#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khandekar0000021@gmail.com
spring.mail.password=rhzh wsry hygq nuwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requires=true
